services:
  - type: web
    name: mental-health-api
    runtime: python
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers"
    plan: standard
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: "3.11.9"
    buildCommand: "pip install -r requirements.txt"
    rootDir: Backend
    healthCheckPath: /health
    healthCheckInterval: 300
    autoDeploy: true
    region: oregon
    registryCredential: null
    dockerfilePath: null

  - type: static
    name: mental-health-frontend
    buildCommand: "npm ci && npm run build"
    staticPublishPath: build
    buildFilter:
      paths:
        - Frontend/**
    rootDir: Frontend
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: mental-health-api
          property: url
          path: /api
    autoDeploy: true
    region: oregon
